export const CREATE_TENANT = "create-tenant"
export const DELETE_TENANT = "delete-tenant"
export const MODIFY_TENANT = "modify-tenant"
export const NEW_ORDER = "newOrder"
export const GET_ALL_TENANTS = "get-all-tenants"